
version: 2.1

jobs:
  # SonarQube analysis (updated with coverage report)
  sonar-analysis:
    docker:
      - image: sonarsource/sonar-scanner-cli
    steps:
      - checkout
            # Install dependencies
      - run:
          name: Install dependencies
          command: yarn 

      # Run tests with coverage reporting
      - run:
          name: Run tests with coverage
          command: yarn jest --coverage

      # Upload coverage report to CircleCI (optional)
      - run:
          name: Upload coverage report
          command: circleci circle-artifact upload --path=coverage.lcov --tag=coverage
      # Run SonarQube Scanner
      - run:
          name: Run SonarQube Scanner
          command: |
            sonar-scanner \
              -Dsonar.projectKey=Type-script \
              -Dsonar.sources=. \
              -Dsonar.inclusions=**/* \
              -Dsonar.host.url=http://65.1.31.213:9000 \
              -Dsonar.coverage.reportPaths=coverage/lcov.info \
              -Dsonar.token=$SONAR_TOKEN

workflows:
  build-and-analyze:
    jobs:
      - sonar-analysis

